title NixOS
sort-key nixos
version Generation 79 NixOS Xantusia 25.11.20251112.c5ae371 (Linux 6.17.7), built on 2026-05-01
linux /EFI/nixos/snbvccl5hpnpixyq0qf1pkimjpzxv2rb-linux-asahi-6.17.7-Image.efi
initrd /EFI/nixos/h4c8l58pl3mchpap70xai93abbhw456g-initrd-linux-asahi-6.17.7-initrd.efi
options init=/nix/store/ymv2nphbm55a8lrwa2spm47p0fmvlpjm-nixos-system-dogeOnArm-25.11.20251112.c5ae371/init earlycon console=tty0 boot.shell_on_fail nvme_apple.flush_interval=0 loglevel=4 lsm=landlock,yama,bpf
machine-id b04e56b782bc43c98791d081ab10c5b3
